<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Global helper / facade guard
|--------------------------------------------------------------------------
|
| Every entry point requires this file instead of vendor/autoload.php.
| Laravel declares its helpers behind `function_exists()`, and Composer
| autoloads Illuminate\Support\Facades\Facade lazily, so declaring both
| here first means the framework's own files are never loaded.
|
| The guarded file is generated by bootstrap/guarded-framework.php from
| Composer's post-autoload-dump; see there for its contents. Its name carries
| a hash of installed.json and the generator, so a missing file here means
| Composer's scripts have not run since the last change. Static methods that
| really exist on the base class (swap(), shouldReceive(), ...) are only
| covered by LibConfig\PhpStan\NoFacadeRule.
|
*/

namespace LaravelOrbStack {
    use LogicException;
    use RuntimeException;

    /**
     * Project directories that may call facades: vendor/ is the framework
     * calling itself, config/ is evaluated before the container exists.
     */
    const ALLOWED = ['vendor/', 'config/'];

    /**
     * Helpers are also allowed from compiled Blade, which includes Laravel's
     * own error pages (they call __()) and has lost its source path.
     */
    const HELPER_ALLOWED = [...ALLOWED, 'storage/framework/views/'];

    /** Frames guard_helper() walks: enough for chains like abort_if() -> abort() -> app(). */
    const HELPER_FRAMES = 6;

    /** Path prefix of the generated file; the input hash and `.php` follow. */
    const GUARDED = __DIR__ . '/cache/guarded-framework-';

    /**
     * Throws when $frame is project code outside $allowed. The guarded file
     * counts as the framework: its helpers call facades (now() -> Date::now()).
     *
     * @param array{file?: string, line?: int} $frame
     * @param list<string> $allowed directories relative to the project root
     */
    function reject_app_call(string $call, array $frame, array $allowed): void
    {
        $file = $frame['file'] ?? '';
        $root = \dirname(__DIR__) . '/';

        if (! str_starts_with($file, $root) || str_starts_with($file, GUARDED)) {
            return;
        }

        foreach ($allowed as $directory) {
            if (str_starts_with($file, $root . $directory)) {
                return;
            }
        }

        throw new LogicException(\sprintf(
            '%s called from %s:%d: inject the underlying contract instead.',
            $call,
            $file,
            $frame['line'] ?? 0,
        ));
    }

    function guard_helper(): void
    {
        // Frame 0 is this call; frames in GUARDED are helpers calling helpers
        // (abort_if() -> abort() -> app(), ...), so the first frame outside is
        // the code that wrote the outermost helper call and its `function` is
        // the helper the user actually wrote.
        foreach (\array_slice(debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, HELPER_FRAMES), 1) as $frame) {
            $file = $frame['file'] ?? null;

            if ($file === null || str_starts_with($file, GUARDED)) {
                continue;
            }

            reject_app_call(\sprintf('Global helper %s()', $frame['function']), $frame, HELPER_ALLOWED);

            return;
        }
    }

    $generator = __DIR__ . '/guarded-framework.php';
    $file = GUARDED . hash('xxh128', hash_file('xxh128', $generator) . hash_file('xxh128', \dirname(__DIR__) . '/vendor/composer/installed.json')) . '.php';

    // Generating here would put a writer and its races on the request path.
    if (! is_file($file)) {
        throw new RuntimeException(\sprintf('%s is missing or stale: run `composer dump-autoload`.', $file));
    }

    require $file;
}

namespace Illuminate\Support\Facades {
    /**
     * @mago-expect lint:file-name
     */
    abstract class Facade extends VendorFacade
    {
        /**
         * @param array<int, mixed> $args
         */
        public static function __callStatic($method, $args): mixed
        {
            // Frame 0 is the code that wrote `Foo::bar()`; the framework's own
            // facade calls (HasTimestamps -> Date::now(), ...) come from vendor/.
            // Compiled Blade stays covered here: static analysis never sees it.
            \LaravelOrbStack\reject_app_call(
                \sprintf('Facade %s::%s()', static::class, $method),
                debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 1)[0] ?? [],
                \LaravelOrbStack\ALLOWED,
            );

            return parent::__callStatic($method, $args);
        }
    }
}

namespace {
    return require __DIR__ . '/../vendor/autoload.php';
}
