#!/usr/bin/env php
<?php
declare(strict_types=1);

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

require __DIR__ . '/bootstrap/autoload.php';

$app = require __DIR__ . '/bootstrap/app.php';
assert($app instanceof Application, Application::class . ' is required.');

$status = $app->handleCommand(new ArgvInput());

exit($status);
