# fly.toml app configuration file generated for html2 on 2024-04-28T13:39:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'html2'
primary_region = 'nrt'
console_command = 'php /var/www/html/artisan tinker'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
