name: ci
x-common-settings: &healthcheck-settings
  interval: 1s
  timeout: 30s
  retries: 30
networks:
  orb:
    ipam:
      driver: default
      config:
        - subnet: 192.168.198.0/24
          gateway: 192.168.198.1
services:
  postgresql:
    volumes: !override
      - type: bind
        source: ./local/db/script.sql
        target: /docker-entrypoint-initdb.d/script.sql
    networks:
      orb:
        ipv4_address: 192.168.198.10

  mysql:
    volumes: !reset []
    networks:
      orb:
        ipv4_address: 192.168.198.9

  cache:
    volumes: !reset []
    networks:
      orb:
        ipv4_address: 192.168.198.8

  session:
    volumes: !reset []
    networks:
      orb:
        ipv4_address: 192.168.198.7

  storage:
    networks:
      orb:
        ipv4_address: 192.168.198.6

  mail:
    networks:
      orb:
        ipv4_address: 192.168.198.5

  php-app: !reset []

  php-franken: !reset []

  php-cli: !reset []

  balancer: !reset []
