name: laravelorbstack
x-common-settings: &healthcheck-settings
  interval: 1s
  timeout: 30s
  retries: 30

services:
  postgresql:
    networks:
      default:
        aliases:
          - laravelorbstack.pgsql.local
    ports:
      - "127.0.0.1:5432:5432"
    image: postgres:18.0-alpine3.22@sha256:48c8ad3a7284b82be4482a52076d47d879fd6fb084a1cbfccbd551f9331b0e40
    container_name: laravelorbstack-postgresql
    environment:
      POSTGRES_DB: sample
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: sample
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - type: bind
        source: ./local/db/script.sql
        target: /docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: [
        "CMD",
        "pg_isready",
        "-h",
        "laravelorbstack.pgsql.local",
        "-U",
        "sample",
        "-d",
        "sample",
        "-p",
        "5432",
      ]
      <<: *healthcheck-settings

  mysql:
    networks:
      default:
        aliases:
          - laravelorbstack.mysql.local
    ports:
      - "127.0.0.1:3306:3306"
    image: mysql:9.5.0@sha256:569c4128dfa625ac2ac62cdd8af588a3a6a60a049d1a8d8f0fac95880ecdbbe5
    container_name: laravelorbstack-mysql
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [
        "CMD",
        "mysqladmin",
        "ping",
        "-h",
        "laravelorbstack.mysql.local",
        "-u",
        "sample",
        "-psample",
        "-P",
        "3306",
      ]
      <<: *healthcheck-settings

  cache:
    networks:
      default:
        aliases:
          - laravelorbstack.cache.local
    ports:
      - "127.0.0.1:6379:6379"
    image: redis:8.2.3-alpine3.22@sha256:28c9c4d7596949a24b183eaaab6455f8e5d55ecbf72d02ff5e2c17fe72671d31
    container_name: laravelorbstack-cache
    command: redis-server --appendonly yes
    healthcheck:
      test: [
        "CMD",
        "redis-cli",
        "ping"
      ]
      <<: *healthcheck-settings

  session:
    networks:
      default:
        aliases:
          - laravelorbstack.session.local
    ports:
      - "127.0.0.1:6380:6379"
    image: redis:8.2.3-alpine3.22@sha256:28c9c4d7596949a24b183eaaab6455f8e5d55ecbf72d02ff5e2c17fe72671d31
    container_name: laravelorbstack-session
    command: redis-server --appendonly yes
    healthcheck:
      test: [
        "CMD",
        "redis-cli",
        "ping"
      ]
      <<: *healthcheck-settings

  mail:
    networks:
      default:
        aliases:
          - laravelorbstack.mail.local
    ports:
      - "127.0.0.1:9000:9000"
    image: axllent/mailpit:v1.27.11@sha256:e22dce5b36f93c77082e204a3942fb6b283b7896e057458400a4c88344c3df68
    container_name: laravelorbstack-mail
    healthcheck:
      test: [
        "CMD",
        "ping",
        "-c",
        "3",
        "laravelorbstack.mail.local"
      ]
      <<: *healthcheck-settings

  storage:
    networks:
      default:
        aliases:
          - laravelorbstack.storage.local
          - sample-bucket.laravelorbstack.storage.local
    ports:
      - "127.0.0.1:8025:8025"
      - "127.0.0.1:1025:1025"
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e
    container_name: laravelorbstack-storage
    command: server /export --console-address ":80"
    environment:
      # @see https://min.io/docs/minio/linux/reference/minio-server/settings/core.html#domain
      MINIO_DOMAIN: laravelorbstack.storage.local
      MINIO_ROOT_USER: samplesample
      MINIO_ROOT_PASSWORD: samplesample
    healthcheck:
      test: [
        "CMD",
        "curl",
        "-I",
        "laravelorbstack.storage.local/minio/health/live"
      ]
      <<: *healthcheck-settings

  setUpStorage:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z@sha256:a7fe349ef4bd8521fb8497f55c6042871b2ae640607cf99d9bede5e9bdf11727
    depends_on:
      storage:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://laravelorbstack.storage.local:9000 samplesample samplesample;
      mc mb myminio/sample-bucket;
      mc anonymous set public myminio/sample-bucket;
      exit 0;
      "
    profiles:
      - bucket
