name: laravelorbstack
x-common-settings: &healthcheck-settings
  interval: 1s
  timeout: 30s
  retries: 30

services:
  postgresql:
    volumes: !override
      - type: bind
        source: ./local/db/script.sql
        target: /docker-entrypoint-initdb.d/script.sql
    ports:
      - "127.0.0.1:5432:5432"

  mysql:
    volumes: !reset []
    ports: !override
      - "127.0.0.1:3306:3306"

  cache:
    volumes: !reset []
    ports: !override
      - "127.0.0.1:6379:6379"

  session:
    volumes: !reset []
    ports: !override
      - "127.0.0.1:6380:6379"

  storage:
    ports: !override
      - "127.0.0.1:8025:8025"
      - "127.0.0.1:1025:1025"

  php-app: !reset []

  php-franken: !reset []

  php-cli: !reset []

  balancer: !reset []
